# Generated by Django 4.1.7 on 2023-03-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('austineblog', '0003_post2_delete_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
